language: bash
sudo: required

services:
  - docker

env:
  global:
    - repo_name=tumgis
    - image_name=3dcitydb-web-map

  matrix:
    # debian versions
    - webmapclient_version: v1.1.0
      baseimage_tag: 10
      tag: v1.1.0
      dockerfile: .
    - webmapclient_version: v1.4.0
      baseimage_tag: 10
      tag: v1.4.0
      dockerfile: .
    - webmapclient_version: v1.6.0
      baseimage_tag: 10
      tag: v1.6.0
      dockerfile: .
    - webmapclient_version: v1.6.1
      baseimage_tag: 10
      tag: v1.6.1
      dockerfile: .
    - webmapclient_version: v1.6.2
      baseimage_tag: 10
      tag: v1.6.2
      dockerfile: .
    - webmapclient_version: v1.7.1
      baseimage_tag: 10
      tag: v1.7.1,latest
      dockerfile: .
    - webmapclient_version: master
      baseimage_tag: 10
      tag: experimental
      dockerfile: .
    # alpine versions
    - webmapclient_version: v1.1.0
      baseimage_tag: 10-alpine
      tag: v1.1.0
      dockerfile: alpine
    - webmapclient_version: v1.4.0
      baseimage_tag: 10-alpine
      tag: v1.4.0
      dockerfile: alpine
    - webmapclient_version: v1.6.0
      baseimage_tag: 10-alpine
      tag: v1.6.0
      dockerfile: alpine
    - webmapclient_version: v1.6.1
      baseimage_tag: 10-alpine
      tag: v1.6.1
      dockerfile: alpine
    - webmapclient_version: v1.6.2
      baseimage_tag: 10-alpine
      tag: v1.6.2
      dockerfile: alpine
    - webmapclient_version: v1.7.1
      baseimage_tag: 10-alpine
      tag: v1.7.1,latest
      dockerfile: alpine
    - webmapclient_version: master
      baseimage_tag: 10-alpine
      tag: experimental
      dockerfile: alpine

before_script:
  - chmod +x ./travis.sh
  - ./travis.sh build
  - ./travis.sh runContainer

script:
  - sleep 3  
  - docker logs webcl
  - curl "http://127.0.0.1:8000/3dwebclient/" -s | grep '<title>3DCityDB-Web-Map-Client</title>'  
  - ./travis.sh deploy

after_script:
  - ./travis.sh cleanup

notifications:
    slack: tum-gis:Z32lHXJDXaycOn4643NHSXaT
    on_success: change
    on_failure: always
  